name: Dependency Update

on:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      - name: Set Go Module Path
        run: |
          go env -w GO111MODULE=on
          go env -w GOPROXY=https://proxy.golang.org,direct
          go env -w GOMODCACHE=$HOME/go/pkg/mod
          go env -w GOPATH=$HOME/go
          mkdir -p $GOPATH/src/github.com/ividernvi
          ln -s $GITHUB_WORKSPACE $GOPATH/src/github.com/ividernvi/algohub
          cd $GOPATH/src/github.com/ividernvi/algohub

      - name: Update dependencies
        run: go get -u ./...

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: update dependencies"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}